server:
  port: 8081

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: INFO
  #  level.org.hibernate.SQL: DEBUG
  level.liquibase: INFO
  level.io.fdlessard.codebites.cloud.stream.processor: DEBUG

spring:
  application:
    name: customer-processor-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  sql:
    init:
      mode: never
      platform: postgres
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}
          configuration:
            security.protocol: SASL_SSL
            ssl.endpoint.identification.algorithm: https
            sasl.mechanism: PLAIN
            sasl.jaas.config: ${JAAS_CONFIG}
            request.timeout.ms: 20000
            retry.backoff.ms: 500
      bindings:
        receiveCustomer-in-0:
          destination: customers
          group: customerGroup
          contentType: application/json
        receiveAddress-in-0:
          destination: addresses
          group: addressGroup
          contentType: application/json
    function:
      definition: receiveCustomer;receiveAddress