server:
  port: 8081

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: INFO
  #  level.org.hibernate.SQL: DEBUG
  level.liquibase: INFO
  level.io.fdlessard.codebites.cloud.stream.processor: DEBUG

spring:
  application:
    name: customer-processor-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:postgres}
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true
  cloud:
    stream:
      bindings:
        receiveCustomer-in-0:
          destination: customers
        receiveAddress-in-0:
          destination: addresses
    function:
      definition: receiveCustomer;receiveAddress