server:
  port: 8080

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: DEBUG
  level.liquibase: INFO
  level.io.fdlessard.codebites.cloud.stream.api: DEBUG

spring:
  application:
    name: customer-api-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        time_zone: UTC
    show-sql: true
  liquibase:
    enabled: on
    drop-first: on
    default-schema: public
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  kafka:
    properties:
      sasl:
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='WNYXPXAYKWCE2D4P' password='gSeNyHIsoYgjoorcWsd51Obx47/0dYser0Y7u31boeYrgkGqbZl0j5gje7HzUI7C';"
        mechanism: PLAIN
      bootstrap:
        servers: pkc-ld537.ca-central-1.aws.confluent.cloud:9092
      security:
        protocol:SASL_SSL
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers: pkc-ld537.ca-central-1.aws.confluent.cloud:9092
#          configuration:
#            ssl:
#              endpoint.identification.algorithm: https
#            sasl:
#              mechanism: PLAIN
#              jaas:
#                config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='WNYXPXAYKWCE2D4P' password='gSeNyHIsoYgjoorcWsd51Obx47/0dYser0Y7u31boeYrgkGqbZl0j5gje7HzUI7C';"
#            security:
#              protocol: SASL_SSL
      bindings:
        customer-out-0:
          contentType: application/json
          destination: customers
          useNativeEncoding: true
        address-out-0:
          contentType: application/json
          destination: addresses
          useNativeEncoding: true

customer:
  publishingActivated: true